(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(backward-delete-char-untabify-method nil)
 '(c-basic-offset 4)
 '(c-default-style (quote ((java-mode . "java") (awk-mode . "awk") (other . "bsd"))))
 '(column-number-mode t)
 '(comint-input-ignoredups t)
 '(comint-prompt-read-only t)
 '(comint-scroll-to-bottom-on-input (quote all))
 '(comment-column 0)
 '(comment-style (quote extra-line))
 '(compilation-scroll-output (quote first-error))
 '(confirm-kill-emacs (quote y-or-n-p))
 '(cursor-in-non-selected-windows nil)
 '(custom-safe-themes (quote ("f5995042d91a82e51f47715fe40ad6596bd2b28dd320873f0a789abf09353b99" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "4dacec7215677e4a258e4529fac06e0231f7cdd54e981d013d0d0ae0af63b0c8" default)))
 '(default-input-method "TeX")
 '(diff-default-read-only t)
 '(diff-mode-hook (quote (diff-make-unified)))
 '(diff-switches "-u")
 '(dired-omit-files "^\\.?#\\|^\\.$\\|^\\.[^.].*$")
 '(doxymacs-command-character "\\")
 '(font-lock-maximum-decoration t)
 '(global-hl-line-mode t)
 '(hg-outgoing-repository "default-push")
 '(hg-update-modeline nil)
 '(hs-hide-comments-when-hiding-all nil)
 '(ibuffer-default-sorting-mode (quote major-mode))
 '(ibuffer-formats (quote ((mark modified read-only " " (name 28 28 :left :elide) " " (size 9 -1 :right) " " (mode 16 16 :left :elide) " " filename-and-process) (mark " " (name 16 -1) " " filename))))
 '(ibuffer-movement-cycle nil)
 '(ibuffer-saved-filter-groups nil)
 '(ibuffer-saved-filters nil)
 '(ibuffer-show-empty-filter-groups nil)
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(jit-lock-stealth-time 5)
 '(kill-whole-line t)
 '(matlab-shell-command "octave")
 '(matlab-shell-command-switches nil)
 '(mouse-1-click-follows-link nil)
 '(mouse-1-click-in-non-selected-windows nil)
 '(mouse-drag-copy-region t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount (quote (3 ((shift) . 1) ((control)))))
 '(octave-block-offset 4)
 '(octave-continuation-string "...")
 '(read-quoted-char-radix 16)
 '(same-window-buffer-names (quote ("*Python*" "*Diff*" "*Apropos*" "*shell*" "*mail*" "*inferior-lisp*" "*ielm*" "*scheme*" "*Hg outgoing*" "*Hg incoming*")))
 '(same-window-regexps (quote ("\\*vc-.*\\*" "\\*rsh-[^-]*\\*\\(\\|<[0-9]*>\\)" "\\*telnet-.*\\*\\(\\|<[0-9]+>\\)" "^\\*rlogin-.*\\*\\(\\|<[0-9]+>\\)" "\\*info\\*\\(\\|<[0-9]+>\\)" "\\*gud-.*\\*\\(\\|<[0-9]+>\\)" "\\`\\*Customiz.*\\*\\'")))
 '(scroll-bar-mode (quote right))
 '(size-indication-mode t)
 '(svn-status-hide-unmodified t)
 '(svn-status-verbose t)
 '(tab-width 4)
 '(term-default-fg-color "lavender blush")
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(transient-mark-mode t)
 '(truncate-lines t)
 '(undo-tree-mode-lighter "")
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(vc-hg-log-switches (quote ("-v")))
 '(visible-bell t)
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(wdired-allow-to-change-permissions t)
 '(whitespace-style (quote (tabs spaces trailing lines space-before-tab newline indentation empty space-after-tab space-mark tab-mark newline-mark)))
 '(woman-use-own-frame nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
