(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(backward-delete-char-untabify-method nil)
 '(c-basic-offset 4)
 '(c-default-style (quote ((java-mode . "java") (awk-mode . "awk") (other . "bsd"))))
 '(column-number-mode t)
 '(comint-input-ignoredups t)
 '(comint-prompt-read-only t)
 '(comint-scroll-to-bottom-on-input (quote all))
 '(comment-column 0)
 '(comment-style (quote extra-line))
 '(compilation-scroll-output (quote first-error))
 '(confirm-kill-emacs (quote y-or-n-p))
 '(cursor-in-non-selected-windows nil)
 '(default-input-method "TeX")
 '(diff-default-read-only t)
 '(diff-mode-hook (quote (diff-make-unified)) t)
 '(diff-switches "-u")
 '(dired-omit-files "^\\.?#\\|^\\.$\\|^\\.[^.].*$")
 '(doxymacs-command-character "\\")
 '(eol-mnemonic-dos "(CRLF)")
 '(eol-mnemonic-mac "(CR)")
 '(eol-mnemonic-undecided "(EOL?)")
 '(eol-mnemonic-unix "(LF)")
 '(font-lock-maximum-decoration t)
 '(global-hl-line-mode t)
 '(hg-outgoing-repository "default-push")
 '(hg-update-modeline nil)
 '(hs-hide-comments-when-hiding-all nil)
 '(ibuffer-default-sorting-mode (quote major-mode))
 '(ibuffer-formats (quote ((mark modified read-only " " (name 28 28 :left :elide) " " (size 9 -1 :right) " " (mode 16 16 :left :elide) " " filename-and-process) (mark " " (name 16 -1) " " filename))))
 '(ibuffer-movement-cycle nil)
 '(ibuffer-saved-filter-groups nil)
 '(ibuffer-saved-filters nil)
 '(ibuffer-show-empty-filter-groups nil)
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(jit-lock-stealth-time 5)
 '(kill-whole-line t)
 '(matlab-shell-command "octave")
 '(matlab-shell-command-switches nil)
 '(mouse-1-click-follows-link nil)
 '(mouse-1-click-in-non-selected-windows nil)
 '(mouse-drag-copy-region t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount (quote (3 ((shift) . 1) ((control)))))
 '(octave-block-offset 4)
 '(octave-continuation-string "...")
 '(read-quoted-char-radix 16)
 '(safe-local-variable-values (quote ((eval when (and (buffer-file-name) (file-regular-p (buffer-file-name)) (string-match-p "^[^.]" (buffer-file-name))) (emacs-lisp-mode)) (encoding . utf-8) (emacs-lisp-docstring-fill-column . 78))))
 '(same-window-buffer-names (quote ("*Python*" "*Diff*" "*Apropos*" "*shell*" "*mail*" "*inferior-lisp*" "*ielm*" "*scheme*" "*Hg outgoing*" "*Hg incoming*")))
 '(same-window-regexps (quote ("\\*vc-.*\\*" "\\*rsh-[^-]*\\*\\(\\|<[0-9]*>\\)" "\\*telnet-.*\\*\\(\\|<[0-9]+>\\)" "^\\*rlogin-.*\\*\\(\\|<[0-9]+>\\)" "\\*info\\*\\(\\|<[0-9]+>\\)" "\\*gud-.*\\*\\(\\|<[0-9]+>\\)" "\\`\\*Customiz.*\\*\\'")))
 '(scroll-bar-mode (quote right))
 '(size-indication-mode t)
 '(svn-status-hide-unmodified t)
 '(svn-status-verbose t)
 '(term-default-fg-color "lavender blush")
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(transient-mark-mode t)
 '(truncate-lines t)
 '(undo-tree-mode-lighter "")
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(vc-hg-log-switches (quote ("-v")))
 '(visible-bell t)
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(wdired-allow-to-change-permissions t)
 '(whitespace-style (quote (tabs spaces trailing lines space-before-tab newline indentation empty space-after-tab space-mark tab-mark newline-mark)))
 '(woman-use-own-frame nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "gray12" :foreground "green" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(ac-candidate-face ((t (:background "grey15" :foreground "lavender"))))
 '(ac-completion-face ((t (:foreground "green4"))))
 '(ac-selection-face ((t (:background "grey10" :foreground "magenta"))))
 '(ack-file ((((background dark)) (:foreground "red2"))))
 '(ack-match ((nil (:foreground "orange" :underline t))))
 '(custom-button ((((type x w32 mac) (class color)) (:underline t :weight bold))))
 '(custom-button-mouse ((((type x w32 mac) (class color)) (:inherit (custom-button highlight)))))
 '(custom-button-pressed ((((type x w32 mac) (class color)) (:inherit custom-button :underline nil))))
 '(custom-button-unraised ((t (:inherit custom-button :underline nil))))
 '(diff-added ((t (:inherit diff-changed :foreground "green2"))))
 '(diff-refine-change ((((class color) (min-colors 88) (background dark)) (:background "grey25"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "red3"))))
 '(diredp-dir-heading ((t (:background "grey10" :foreground "magenta"))))
 '(diredp-dir-priv ((t (:foreground "CornFlowerBlue"))))
 '(diredp-display-msg ((t (:foreground "LightBlue"))))
 '(diredp-exec-priv ((t (:foreground "red2"))))
 '(diredp-file-name ((t nil)))
 '(diredp-flag-mark-line ((t (:background "grey10"))))
 '(diredp-inode+size ((t (:foreground "LightBlue4"))))
 '(diredp-link-priv ((t (:foreground "Cyan"))))
 '(diredp-no-priv ((t nil)))
 '(diredp-other-priv ((t (:foreground "violet"))))
 '(diredp-rare-priv ((t (:foreground "Magenta"))))
 '(diredp-read-priv ((t (:foreground "lightgreen"))))
 '(diredp-symlink ((t (:foreground "Cyan"))))
 '(diredp-write-priv ((t (:foreground "yellow2"))))
 '(eldoc-highlight-function-argument ((t (:inherit font-lock-variable-name-face))))
 '(fixed-pitch ((t (:family "DejaVu Sans Mono"))))
 '(flyspell-duplicate ((t (:underline "orange"))))
 '(flyspell-incorrect ((t (:underline "red"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "sandy brown"))))
 '(font-lock-fixme-face ((t (:foreground "Red" :weight bold))))
 '(font-lock-warning-face ((t (:foreground "red3" :weight bold))))
 '(fringe ((t (:background "grey10" :foreground "darkgreen"))))
 '(hi-blue ((((background dark)) (:foreground "light blue" :inverse-video t))))
 '(hi-green ((((min-colors 88) (background dark)) (:foreground "green1" :inverse-video t))))
 '(hi-pink ((((background dark)) (:foreground "pink" :inverse-video t))))
 '(hi-yellow ((((min-colors 88) (background dark)) (:foreground "yellow1" :inverse-video t))))
 '(hl-line ((t (:background "black"))))
 '(ido-first-match ((t (:foreground "magenta"))))
 '(ido-only-match ((t (:foreground "magenta" :slant italic))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "cyan"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line-highlight ((t (:box (:line-width 1 :color "gray12")))))
 '(modelinepos-column-warning ((t (:inherit font-lock-warning-face))))
 '(modelinepos-region ((t (:inverse-video t))))
 '(mouse ((t (:background "white"))))
 '(mouse-flash-position ((t (:background "grey75"))))
 '(mouse-scan-lines ((t (:background "grey33"))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode1 ((((class color) (min-colors 88) (background dark)) (:background "grey15"))))
 '(mumamo-background-chunk-submode2 ((((class color) (min-colors 88) (background dark)) (:background "grey20"))))
 '(mumamo-background-chunk-submode3 ((((class color) (min-colors 88) (background dark)) (:background "grey25"))))
 '(mumamo-background-chunk-submode4 ((((class color) (min-colors 88) (background dark)) (:background "grey30"))))
 '(pulldown-default-face ((t (:background "gray15" :foreground "lavender"))))
 '(pulldown-default-selection-face ((t (:background "grey10" :foreground "magenta"))))
 '(show-paren-match ((t (:background "grey12" :inverse-video t))))
 '(whitespace-empty ((t (:foreground "firebrick"))))
 '(whitespace-hspace ((((class color) (background dark)) (:foreground "aquamarine3"))))
 '(whitespace-indentation ((t (:foreground "firebrick"))))
 '(whitespace-line ((t (:foreground "violet"))))
 '(whitespace-space ((((class color) (background dark)) (:foreground "aquamarine3"))))
 '(whitespace-space-after-tab ((t (:foreground "firebrick"))))
 '(whitespace-space-before-tab ((t (:foreground "firebrick"))))
 '(whitespace-tab ((((class color) (background dark)) (:foreground "aquamarine3"))))
 '(whitespace-trailing ((t (:foreground "yellow" :weight bold)))))
